### ISSUE TITLE
Duboku error, check the log for more information

### ISSUE THREAD

**Issue by Waterman88** [groggyegg/plugin.video.duboku#16]
Still having error with plugin 3.1.1. Issue #14 did not get fixed by #15 with the new release.

**Comment by groggyegg** [comment]
Do you have logs? I have tested and it works for me.

**Comment by Waterman88** [comment]
How can I get the log and send to you?  Please advise.

  I tested on PC, Sony Android TV and Onn box.  All got the same error.
The version from jianmira is still working.  But not the 3.1.1.

**Comment by Waterman88** [comment]
Here is what i got from the Kodi.log:

2024-02-27 12:50:35.591 T:19600    info <general>: [script.module.xbmcext]
Routing "/"
2024-02-27 12:50:35.591 T:19600    info <general>: [script.module.xbmcext]
Calling "home"
2024-02-27 12:50:41.793 T:17444    info <general>: [script.module.xbmcext]
Routing "/www.duboku.tv"
2024-02-27 12:50:41.794 T:17444    info <general>: [script.module.xbmcext]
Calling "wwwdubokutv"
2024-02-27 12:50:45.278 T:34036    info <general>: [script.module.xbmcext]
Routing "/www.duboku.tv/vodshow/2-----------.html?id=2"
2024-02-27 12:50:45.279 T:34036    info <general>: [script.module.xbmcext]
Calling "vodshow_filter"
2024-02-27 12:50:45.289 T:32060    info <general>: Loading skin file:
C:\Users\kkng8_000\AppData\Roaming\Kodi\addons\script.module.xbmcext\.\resources\skins\Default\1080i\MultiSelectTabDialog.xml,
load type: LOAD_ON_GUI_INIT
2024-02-27 12:50:48.923 T:34036    info <general>: [script.module.xbmcext]
Routing "/www.duboku.tv/vodshow/2-内地-time---------.html
<http://www.duboku.tv/vodshow/2-%E5%86%85%E5%9C%B0-time---------.html>"
2024-02-27 12:50:48.924 T:34036    info <general>: [script.module.xbmcext]
Calling "vodshow"
2024-02-27 12:50:48.924 T:34036    info <general>: [plugin.video.duboku]
GET "https://www.duboku.tv/vodshow/2-内地-time---------.html"
2024-02-27 12:50:49.087 T:34036   error <general>: EXCEPTION Thrown
(PythonToCppException) : -->Python callback/script returned the following
error<--
                                                    - NOTE: IGNORING THIS
CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class
'Exception'>
                                                   Traceback (most recent
call last):
                                                     File
"C:\Users\kkng8_000\AppData\Roaming\Kodi\addons\plugin.video.duboku\duboku\addon.py",
line 357, in <module>
                                                       plugin()
                                                     File
"C:\Users\kkng8_000\AppData\Roaming\Kodi\addons\script.module.xbmcext\.\xbmcext\__init__.py",
line 491, in __call__
                                                       function(**kwargs)
                                                     File
"C:\Users\kkng8_000\AppData\Roaming\Kodi\addons\plugin.video.duboku\duboku\addon.py",
line 283, in vodshow_filter
                                                       plugin.redirect(path)
                                                     File
"C:\Users\kkng8_000\AppData\Roaming\Kodi\addons\script.module.xbmcext\.\xbmcext\__init__.py",
line 588, in redirect
                                                       self()
                                                     File
"C:\Users\kkng8_000\AppData\Roaming\Kodi\addons\script.module.xbmcext\.\xbmcext\__init__.py",
line 491, in __call__
                                                       function(**kwargs)
                                                     File
"C:\Users\kkng8_000\AppData\Roaming\Kodi\addons\plugin.video.duboku\duboku\addon.py",
line 289, in vodshow
                                                       shows, pages =
Request.vodshow(plugin.path)
                                                     File
"C:\Users\kkng8_000\AppData\Roaming\Kodi\addons\plugin.video.duboku\duboku\request.py",
line 74, in vodshow
                                                       doc =
BeautifulSoup(cls.get(path), 'html.parser', parse_only=parse_only)
                                                     File
"C:\Users\kkng8_000\AppData\Roaming\Kodi\addons\plugin.video.duboku\duboku\request.py",
line 46, in get
                                                       raise Exception()
                                                   Exception
                                                   -->End of Python script
error report<--

2024-02-27 12:50:49.271 T:22392   error <general>:
XFILE::CDirectory::GetDirectory - Error getting
plugin://plugin.video.duboku/www.duboku.tv/vodshow/2-----------.html?id=2
2024-02-27 12:50:49.276 T:32060   error <general>:
CGUIMediaWindow::GetDirectory(plugin://plugin.video.duboku/
www.duboku.tv/vodshow/2-----------.html?id=2) failed


<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by Waterman88** [comment]
I tested it again.  The Sony Android TV, Onn TV Box are fine now.  Still have problem on PC.  It is a fresh Kodi and duboku install.

**Comment by groggyegg** [comment]
The error seems to indicate that you can’t access the website. Can you access duboku.tv on web browser?

**Comment by Waterman88** [comment]
Yes. I can access it from my PC web browser.  Seems it is only not working
on my Windows 10 PC.  You can close this issue.

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by kin2son** [comment]
Looks like the issue has come back on android TV....:(
