### ISSUE TITLE
duboku has changed the domain name, so it does not work

### ISSUE THREAD

**Issue by NetBoy855** [groggyegg/plugin.video.duboku#19]
Duboku does not work because the domain name of the play page of duboku.tv has been changed. The new domain name is tv.gboku.com

**Comment by jaajaajaajann** [comment]
Do you have a fix?

**Comment by groggyegg** [comment]
This issue is probably no longer valid since I can still access duboku.tv, otherwise reopen it.

**Comment by jaajaajaajann** [comment]
Just tried it on the fire stick still getting an error. I agree that the
main website duboku.tv does load but after you select a show and try to
play a video the domain changes to TV.gboku.com. see. Screenshots below
from my phone.
