### ISSUE TITLE
Addon cannot be used

### ISSUE THREAD

**Issue by jieni0123** [groggyegg/plugin.video.duboku#5]
Hi, this duboku addon is not longer able to use in Kodi. And I discover that when enter duboku.com in browser it will automatically direct to duboku.tv. Can you fix the addon again? Thanks ya!

**Comment by groggyegg** [comment]
Thanks for informing. I will check on it during the weekends.

**Comment by groggyegg** [comment]
Only the Movies are affected but the rest seems to work.

**Comment by Sawadee2u** [comment]
Kodi 20.0 still an issue. All works except Movies.

**Comment by groggyegg** [comment]
Thanks, haven't had time to fix the addon. But will update it after dramacool fix

**Comment by groggyegg** [comment]
Just checked their website, movies has been removed from their site so I will remove it from the addon instead.
