### ISSUE TITLE
Using duboku.su

### ISSUE THREAD

**Issue by abc8748** [groggyegg/plugin.video.duboku#6]
Hi, may i ask if it possible to change the current duboku.com to duboku.su? Because i discover that duboku.su has more contents and is more updated compare to duboku.com. Besides, sometimes we need to configure DNS to bypass and enter duboku.com. It would be glad if you can take some time to make a plugin for duboku.su. thanks!

**Comment by groggyegg** [comment]
#3 Duplicate
