### ISSUE TITLE
Kodi 20

### ISSUE THREAD

**Issue by rainbatt** [groggyegg/plugin.video.duboku#7]
Will this be supported for Kodi 20?  Tks

**Comment by groggyegg** [comment]
I think it already works.

**Comment by rainbatt** [comment]
Seems not working for me

**Comment by groggyegg** [comment]
It seems the video does not get resolved correctly. I have made a PR to resolveurl. So someone has to do a PR with resolvurl change or wait for when I'm done with the larger change of addon.

**Comment by rainbatt** [comment]
Thanks
